version: '3.1'

services:

  db:
    # image: mcr.microsoft.com/mssql/server:2019-latest
    # environment:
    #   - ACCEPT_EULA=Y
    #   - SA_PASSWORD=yourStrong1234!Password
    image: custom-mssql
    container_name: custom-mssql
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
    - "1433:1433"     